import type { Project } from "./columns";

export const mockProjects: Project[] = [
  {
    id: "proj-001",
    clientName: "Acme Corporation",
    email: "contact@acme.com",
    category: "web",
    priority: "high",
    status: "in_progress",
    createdDate: "2025-12-15",
  },
  {
    id: "proj-002",
    clientName: "TechStart Inc",
    email: "hello@techstart.io",
    category: "mobile",
    priority: "medium",
    status: "pending",
    createdDate: "2025-12-18",
  },
  {
    id: "proj-003",
    clientName: "DesignHub Agency",
    email: "projects@designhub.co",
    category: "ui_ux",
    priority: "high",
    status: "completed",
    createdDate: "2025-11-20",
  },
  {
    id: "proj-004",
    clientName: "GlobalTech Solutions",
    email: "info@globaltech.com",
    category: "web",
    priority: "low",
    status: "pending",
    createdDate: "2025-12-28",
  },
  {
    id: "proj-005",
    clientName: "StartupXYZ",
    email: "founder@startupxyz.com",
    category: "mobile",
    priority: "high",
    status: "in_progress",
    createdDate: "2025-12-10",
  },
  {
    id: "proj-006",
    clientName: "Creative Minds Co",
    email: "team@creativeminds.io",
    category: "ui_ux",
    priority: "medium",
    status: "cancelled",
    createdDate: "2025-11-05",
  },
  {
    id: "proj-007",
    clientName: "E-Commerce Plus",
    email: "support@ecomplus.com",
    category: "web",
    priority: "high",
    status: "completed",
    createdDate: "2025-10-22",
  },
  {
    id: "proj-008",
    clientName: "FinTech Innovations",
    email: "dev@fintech-innov.com",
    category: "mobile",
    priority: "medium",
    status: "in_progress",
    createdDate: "2025-12-01",
  },
  {
    id: "proj-009",
    clientName: "HealthApp Solutions",
    email: "contact@healthapp.org",
    category: "mobile",
    priority: "low",
    status: "pending",
    createdDate: "2026-01-02",
  },
  {
    id: "proj-010",
    clientName: "RetailMax Group",
    email: "digital@retailmax.net",
    category: "web",
    priority: "medium",
    status: "in_progress",
    createdDate: "2025-12-20",
  },
];
