/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitProjectRouteImport } from './routes/submit-project'
import { Route as AiConsultantRouteImport } from './routes/ai-consultant'
import { Route as IndexRouteImport } from './routes/index'

const SubmitProjectRoute = SubmitProjectRouteImport.update({
  id: '/submit-project',
  path: '/submit-project',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConsultantRoute = AiConsultantRouteImport.update({
  id: '/ai-consultant',
  path: '/ai-consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-consultant': typeof AiConsultantRoute
  '/submit-project': typeof SubmitProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-consultant': typeof AiConsultantRoute
  '/submit-project': typeof SubmitProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-consultant': typeof AiConsultantRoute
  '/submit-project': typeof SubmitProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-consultant' | '/submit-project'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-consultant' | '/submit-project'
  id: '__root__' | '/' | '/ai-consultant' | '/submit-project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConsultantRoute: typeof AiConsultantRoute
  SubmitProjectRoute: typeof SubmitProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-project': {
      id: '/submit-project'
      path: '/submit-project'
      fullPath: '/submit-project'
      preLoaderRoute: typeof SubmitProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-consultant': {
      id: '/ai-consultant'
      path: '/ai-consultant'
      fullPath: '/ai-consultant'
      preLoaderRoute: typeof AiConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConsultantRoute: AiConsultantRoute,
  SubmitProjectRoute: SubmitProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
